version: '2'
services:
  realworldcms:
    build: .
    ports:
      - "0.0.0.0:13333:13333"
    mem_limit: 300M
    restart: always
    networks:
      internal_network:
        ipv4_address: 10.0.20.10
      out_network:
        ipv4_address: 10.0.30.10

  mongodb:
    image: mongo
    ports:
      - "0.0.0.0:27017:27017"
    restart: always
    networks:
      internal_network:
        ipv4_address: 10.0.20.12

networks:
  internal_network:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 10.0.20.0/24
  out_network:
    ipam:
      driver: default
      config:
        - subnet: 10.0.30.0/24
